### ISSUE TITLE
✨ [Feature] User Detail API

### ISSUE THREAD

**Issue by ssu-uky** [wanted-A/GIS-Restaurant#3]
## Description
`get` `put` `delete`

## Todo
- [x] 사용자 정보 (password 제외한 모든 정보)
- [x] 사용자의 위치 - **로그인 시 사용자의 위치에 따라 변경됨**
- [x] 사용자 정보 업데이트 
- [x] 사용자 정보 삭제(탈퇴)

## 기타 사항
위도와 경도는 put으로 수정할 수 없으며, 사용자가 위치한 곳의 위도와 경도가 입력됩니다.
