### ISSUE TITLE
✨ [Feature] 대규모 트래픽 대비 캐싱

### ISSUE THREAD

**Issue by mireu-san** [wanted-A/GIS-Restaurant#35]
## Description
redis 를 연동해서, 가능한 만큼 구현 해 보고자 합니다.

## Todo
- 최우선 : API가 호출 될 때, 캐시에 저장되었는지 확인.

**Comment by allen9535** [comment]
feature/jeongheon/#35 브랜치에 Redis 연동을 통해 시군구 목록 저장·목록 조회 기능 관련 고도화 코드 업로드 완료했습니다!
괜찮으시다면 확인 후 피드백 부탁드리겠습니다!

**Comment by allen9535** [comment]
- [x] 시군구 목록 고도화: 시군구 목록에 대해 만료 기간이 없는 캐싱을 진행합니다.
- [x] 1단계: API가 호출될 때 데이터가 캐싱 되었는지 여부를 확인한 다음, 캐싱되었을 경우 캐싱 데이터를, 캐싱되지 않았을 경우 DB에서 데이터를 불러와 캐싱한 다음 데이터를 반환합니다.(만료시간을 설정해야 합니다.)
- [ ] 2단계: 맛집 데이터 API에서 모든 데이터를 캐싱하는 것이 아니라 인기있는 / 추천율이 높은 맛집만 캐싱합니다.

**Comment by mireu-san** [comment]
@allen9535 괜찮은것 같다고 생각됩니다 :)

**Comment by mireu-san** [comment]
feature/chesed/#35 브렌치의 경우, 설정은 feature/jeongheon/#35 로 통일 시킨 후, postgresql 로 db 변경 후 임의로 생성한 로컬 환경 내 test DB에 migrate 하려 했지만 데이터가 DB에 저장이 안되는 것 같아 원인을 찾아보고 있습니다. 다만 조회수 부분은 해당 3개 식당 유형 외부 API 에서 찾을 수 없어, 임의로 location 에 가칭 `views = models.IntegerField(default=0, verbose_name="조회 수")` 를 생성 후, 인기 맛집 (조회수 순) 조회 로직을 구상 해 본 단계였습니다.

지금 이 글을 남기는 현재 시점에서는 celery 에서 restaurants.tasks 가 실행만 되고 db 에 저장까지는 되지 않는 듯 하니, 이점 참고 바라겠습니다.

수정:
아래와 같이 확인했습니다.
```
[2023-11-08 09:25:04,070: INFO/MainProcess] mingle: searching for neighbors
[2023-11-08 09:25:05,141: INFO/MainProcess] mingle: all alone
[2023-11-08 09:25:05,175: INFO/MainProcess] celery@Luminous ready.
[2023-11-08 09:25:10,241: INFO/MainProcess] Task restaurants.tasks.raw_data_handler[90bece9a-9688-4e0b-a5e8-d2942a1a457a] received
[2023-11-08 09:26:30,171: WARNING/MainProcess] 실행시간: 79.93010973930359
[2023-11-08 09:26:30,183: INFO/MainProcess] Task restaurants.tasks.raw_data_handler[90bece9a-9688-4e0b-a5e8-d2942a1a457a] succeeded in 79.93800000002375s: None
[2023-11-08 09:26:30,189: INFO/MainProcess] Task location.tasks.cache_popular_locations[7884daa8-8a16-40bd-b533-ecd3f99ba4e9] received
[2023-11-08 09:26:30,207: INFO/MainProcess] Task location.tasks.cache_popular_locations[7884daa8-8a16-40bd-b533-ecd3f99ba4e9] succeeded in 0.01600000000325963s: None
```

**Comment by mireu-san** [comment]
정상적으로 migrate 된 걸 확인했습니다. 이 부분은 feature/chesed/#35 에 반영해두겠습니다.
<img width="365" alt="image" src="https://github.com/wanted-A/GIS-Restaurant/assets/67046863/1e8495b7-cd9e-47e9-8850-d2d0147738ca">

참고:
주의할 점은 location 의 인기순 레스토랑만 캐싱하는 부분은 적용 했지만, 그 정보를 받아오는 location 모델 필드값은 임의로 views로 설정 해 두었습니다. 이 점 참고부탁드립니다.

향후 restaurants 에서 캐싱 작업 시 응용 해보겠습니다.
