### ISSUE TITLE
✨ [Feature] 테스트 및 배포 편의성을 위한 도커 적용

### ISSUE THREAD

**Issue by allen9535** [wanted-A/GIS-Restaurant#37]
## Description
Celery, Redis, PostgreSQL 등 여러 툴과의 연동 및 테스트, 향후 배포에 대한 편의성을 향상시키기 위해 도커와 도커 컴포즈를 적용하고자 합니다.

## Todo
- [x] Celery를 별도의 이미지로 만들어 컨테이너로 올리고 비동기 작업을 할 수 있게 만들기
- [x] RabbitMQ를 공식 이미지를 활용하여 컨테이너로 올리고 Celery의 메시지 브로커 역할을 할 수 있게 만들기
- [x] Redis를 공식 이미지를 활용하여 컨테이너로 올리고 캐싱 작업을 할 수 있게 만들기
- [x] PostgreSQL을 공식 이미지를 활용하여 컨테이너로 올리고 DB로 사용하기
- [x] 도커를 종료해도 PostgreSQL의 데이터를 유지할 수 있도록 볼륨 설정하기
