### ISSUE TITLE
✨ [Feature] 데이터 수집

### ISSUE THREAD

**Issue by ssu-uky** [wanted-A/GIS-Restaurant#8]
## Description
데이터 수집

## Todo
- [x] 데이터 수집-처리-저장 과정을 담을 app을 생성한다(appname : dataHandler)
- [x] app 삭제 

## OpenAPI
[공공데이터포털](https://www.data.go.kr/tcs/dss/selectDataSetList.do?dType=API&keyword=%EA%B2%BD%EA%B8%B0%EB%8F%84+%EC%9D%BC%EB%B0%98%EC%9D%8C%EC%8B%9D%EC%A0%90&operator=AND&detailKeyword=&publicDataPk=&recmSe=&detailText=&relatedKeyword=&commaNotInData=&commaAndData=&commaOrData=&must_not=&tabId=&dataSetCoreTf=&coreDataNm=&sort=_score&relRadio=&orgFullName=&orgFilter=&org=&orgSearch=&currentPage=1&perPage=10&brm=&instt=&svcType=&kwrdArray=&extsn=&coreDataNmArray=&pblonsipScopeCode=)
![image](https://github.com/wanted-A/GIS-Restaurant/assets/111492415/dcf4088c-8068-4d5f-829f-cfcc2e375d94)

**Comment by kyeon06** [comment]
데이터 수집 - 저장 - 처리 과정은 모든 팀원들이 OpenAPI를 하나씩 맡아서 개발합니다.

**Comment by ssu-uky** [comment]
dataHandler (app)

- [x] 일반음식점(김밥/도시락) - place **기연**

- [x] 일반음식점(이동조리) - delivery **정헌**

- [x] 일반음식점(카페) -cafe **수현**

**Comment by kyeon06** [comment]
데이터수집/처리/저장 코드를 각자 브랜치에 push해두었습니다. 확인부탁드립니다.
